name: Build and deploy

on:
  schedule:
    # Every monday at 10am utc
    - cron:  "0 10 * * 1"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install jq

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          # Username hardcoded so it doesn't get redacted from the log
          username: tofran
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_REGISTRY_PASSWORD }}

      - name: Build and push
        run: ./build-and-push.sh